### ISSUE TITLE
我安装到linux7.2 不行啊

### ISSUE THREAD

**Issue by xiaoyueraymond** [zhuifengshen/DingtalkChatbot#1]
No package 'libffi' found
c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
 #include <ffi.h>
                 ^
compilation terminated.
error: Setup script exited with error: command 'gcc' failed with exit status 1
[root@localhost DingtalkChatbot-master]# yum install python-devel

**Comment by xiaoyueraymond** [comment]
#yum install -y libffi libffi-devel 就好了  看来是我缺少库

**Comment by zhuifengshen** [comment]
好嘞，有其他问题欢迎随时反馈
