### ISSUE TITLE
我想用来 收到某个发件人的邮件,然后把这邮件标题 发件人 收件人 通过钉钉机器人发到群里提醒

### ISSUE THREAD

**Issue by walkcow** [zhuifengshen/DingtalkChatbot#10]
我想用来 收到某个发件人的邮件,然后把这邮件标题 发件人 收件人 通过钉钉机器人发到群里提醒

其实我是用来做一个 订单提醒功能, 由于我的订单消息都是通过邮件接收,我员工是用ERP系统,同步不及时,所以希望用邮件 转发信息到钉钉 . 提醒 . 

请教使用方法

**Comment by ministp** [comment]
可以使用python 接收邮件，然后判定是否需要转发，然后就可以使用钉钉群发了；
