### ISSUE TITLE
发送的actioncard怎么点击不跳转

### ISSUE THREAD

**Issue by Alisusu** [zhuifengshen/DingtalkChatbot#16]
![image](https://user-images.githubusercontent.com/36145929/66884880-1b000680-f005-11e9-8057-85cefb22ca58.png)
像这样的, 点击之后每次自动跳转, 但是我希望的是这种情况点击后直接请求后端接口统计, 但是不进行跳转. 怎么做?

**Comment by zhuifengshen** [comment]
挑战是钉钉控制的，如果想统计投票，现在新版钉钉支持发起投票了
