### ISSUE TITLE
markdown格式@指定用户不管用啊

### ISSUE THREAD

**Issue by liduang** [zhuifengshen/DingtalkChatbot#19]
<img width="539" alt="3E68704E-7D98-469C-A8E9-D4A5B748CB0F" src="https://user-images.githubusercontent.com/37337756/69794331-05395000-1205-11ea-9880-d845515099ec.png">
<img width="559" alt="3C7FE396-768F-4DD7-BEE1-D84EAD77399C" src="https://user-images.githubusercontent.com/37337756/69794336-05d1e680-1205-11ea-922a-0b4ff3411748.png">

@手机号，文本格式发送能@用户，md不能@用户

**Comment by liduang** [comment]
原来这种灰色的@显示，也算是@了。钉钉桌面端看不到被@，手机端能在@里看到被@了。是不是钉钉对md格式有啥区别对待啊？

**Comment by zhuifengshen** [comment]
除了在at_mobiles列表写上手机号，在消息text内容中也要有@手机号，否则无法@成功。因为@手机号的位置可以在文本中自定义，同时支持@多个人，以便突出对应的人去关注对应的内容。
