### ISSUE TITLE
初始化错误

### ISSUE THREAD

**Issue by jasonyun** [zhuifengshen/DingtalkChatbot#21]
xiaoding = DingtalkChatbot(webhook=webhook, secret=secret)
提示错误
xiaoding = DingtalkChatbot(webhook=webhook, secret=secret)
TypeError: __init__() got an unexpected keyword argument 'secret'

**Comment by jasonyun** [comment]
源码里没有这个变量啊

**Comment by zhuifengshen** [comment]
需要更新到最新版v1.5.0
