### ISSUE TITLE
钉钉机器人最大连接数

### ISSUE THREAD

**Issue by Ares8947** [zhuifengshen/DingtalkChatbot#53]
只开一个进程，结果今天发现钉钉机器人报错
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='oapi.dingtalk.com', port=443): Max retries exceeded with url: /robot/send?access_token=XX(token隐藏) (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000017F89A71C70>: Failed to establish a new connection: [Errno 11002] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

是钉钉更改了链接数了么？之前没问题的

**Comment by thevenomsnake** [comment]
手动改一下源码，见
https://github.com/zhuifengshen/DingtalkChatbot/pull/56

**Comment by zhuifengshen** [comment]
已修复，感谢[thevenomsnake](https://github.com/thevenomsnake)
