### ISSUE TITLE
证书验证失败

### ISSUE THREAD

**Issue by puwow** [zhuifengshen/DingtalkChatbot#54]
突然间就报错：SSL: CERTIFICATE_VERIFY_FAILED
在requests.post加了verify=False绕过去了，是否要把这个参数暴露出来？提升兼容性？还有更好的解决方案吗？

**Comment by zhuifengshen** [comment]
verify=False容易导致中间人攻击，产生这个证书问题，大概率是请求环境证书失效，可以排查一下。常见处理方法：https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
