### ISSUE TITLE
NameError: name 'DtalkChatbot' is not defined  python3.5

### ISSUE THREAD

**Issue by zygmcc** [zhuifengshen/DingtalkChatbot#6]
python3.5 Env:
NameError: name 'DtalkChatbot' is not defined

code:
from dingtalkchatbot.chatbot import DingtalkChatbot
# WebHook地址
webhook = 'https://oapi.dingtalk.com/robot/send?access_token=xxx'
# 初始化机器人小丁
xiaoding = DtalkChatbot(webhook)
# Text消息@所有人
xiaoding.send_text(msg='我就是小丁，小丁就是我！', is_at_all=True)

**Comment by zhuifengshen** [comment]
不是：xiaoding = DtalkChatbot(webhook)，而是：xiaoding = DingtalkChatbot(webhook)
