### ISSUE TITLE
自己个人使用的钉钉号怎么每天自动给领导发祝福语

### ISSUE THREAD

**Issue by fbigun** [zhuifengshen/DingtalkChatbot#8]
（●─●）。翻遍所有文档没看到相关内容。首先我不是企业管理员。我只想在群组里收到 at 的时候自动 回复 "收到，我已在处理中"。

**Comment by yzakzero** [comment]
我自己尝试了一下普通群，非管理员是可以添加机器人的，后面的还需要点时间研究下。

**Comment by zhuifengshen** [comment]
钉钉机器人没有监听群聊天记录的功能，想at你的时候自动回复，这个通过钉钉机器人无法实现
