### ISSUE TITLE
请问下at_dingtalk_ids的说明

### ISSUE THREAD

**Issue by wulvsky** [zhuifengshen/DingtalkChatbot#9]
通过outgoing能够获取到@方的dingtalkid ,无法获取手机号码,不能直接通过at_mobiles
但是通过 at_dingtalk_ids 好像不起作用.

**Comment by zhuifengshen** [comment]
atDingtalkIds指的是被@人的加密用户ID，官方文档地址：https://ding-doc.dingtalk.com/doc#/serverapi2/elzz1p/pvNZZ
